# Generated by Django 4.1.5 on 2023-02-26 11:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_remove_user_watchlist_user_watchlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='watchlist',
        ),
        migrations.AddField(
            model_name='listings',
            name='watchlistMaker',
            field=models.ManyToManyField(null=True, related_name='watchlist', to=settings.AUTH_USER_MODEL),
        ),
    ]
