# Generated by Django 4.1.5 on 2023-02-26 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_remove_user_watchlist_listings_watchlistmaker'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listings',
            name='watchlistMaker',
        ),
    ]
