# Generated by Django 4.1.5 on 2023-02-26 14:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_remove_listings_watchlistmaker'),
    ]

    operations = [
        migrations.CreateModel(
            name='bidding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid', models.IntegerField()),
                ('obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saman', to='auctions.listings')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='juwade', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
