# Generated by Django 4.1.5 on 2023-02-28 13:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_bidding'),
    ]

    operations = [
        migrations.CreateModel(
            name='comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.IntegerField(max_length=500)),
                ('commentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bolne', to=settings.AUTH_USER_MODEL)),
                ('onwhat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sunne', to='auctions.listings')),
            ],
        ),
    ]
