# Generated by Django 4.1.5 on 2023-03-01 10:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_user_watchlist_alter_comments_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='watchlist',
        ),
        migrations.CreateModel(
            name='watchlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity', models.ManyToManyField(blank=True, related_name='dekhaune', to='auctions.listings')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='herne', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
