# Generated by Django 4.1.5 on 2023-03-01 11:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_remove_user_watchlist_watchlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlist',
            name='owner',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='herne', to=settings.AUTH_USER_MODEL),
        ),
    ]
