# Generated by Django 4.1.5 on 2023-03-01 14:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_alter_watchlist_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='listings',
            name='watchlist',
            field=models.ManyToManyField(blank=True, null=True, related_name='cart', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='watchlist',
        ),
    ]
