# Generated by Django 4.1.5 on 2023-03-02 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_listings_watchlist_delete_watchlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='listings',
            name='activity',
            field=models.BooleanField(default=True),
        ),
    ]
