# Generated by Django 4.1.5 on 2023-05-13 13:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='following',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main', to=settings.AUTH_USER_MODEL)),
                ('followers', models.ManyToManyField(blank=True, null=True, related_name='vedas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
