# Generated by Django 4.1.5 on 2023-05-16 10:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_follow_delete_following'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follow',
            name='followed',
        ),
        migrations.AddField(
            model_name='follow',
            name='followed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='beingFollowed', to=settings.AUTH_USER_MODEL),
        ),
    ]
