# Generated by Django 4.1.5 on 2023-05-18 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0007_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='likes',
            name='likesCount',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
