# Generated by Django 4.1.5 on 2023-05-18 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0008_likes_likescount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likes',
            name='likesCount',
        ),
        migrations.AddField(
            model_name='post',
            name='likesCount',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
