# Generated by Django 4.1.5 on 2023-05-18 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0009_remove_likes_likescount_post_likescount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='likesCount',
            field=models.CharField(blank=0, max_length=100, null=True),
        ),
    ]
