# Generated by Django 4.1.5 on 2023-05-18 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0010_alter_post_likescount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='likesCount',
            field=models.CharField(default=0, max_length=100, null=True),
        ),
    ]
