# Generated by Django 4.1.5 on 2023-05-18 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0011_alter_post_likescount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='likesCount',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
