# Generated by Django 4.1.5 on 2023-05-18 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0012_alter_post_likescount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likes',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
